Trading Tests and Demo
========================================================
Paul Sztorc
`r date()`

```{r Load,echo=FALSE,message=FALSE}
#Source
rm(list=ls())

tryCatch(expr=setwd("~/GitHub/Truthcoin/lib"), error=function(e) setwd(choose.dir(caption="Failed to set working directory automatically. Choose 'lib' folder:")) )
source("market/Trading.R")

CreateAccount("Alice",10)
CreateAccount("Bob",50)
Users

names(Markets)

CreateMarket(Title="Obama", B=1, TradingFee=.01,
             D_State=list( "184b97f33923f30a9f586827b400676e" ), #Decisions (just one: will Barack be Elected)
             Description="Barack Obama to win United States President in 2012\nThis Market will expire in state 1 if the statement is true and 0 otherwise.",
             Tags=c("Politics, UnitedStates, President, Winner"),
             OwnerAd="1Loxo4RsiokFYXgpjc4CezGAmYnDwaydWh"
             )

CreateMarket(Title="Hillary", B=2.5, TradingFee=.005,
             D_State=list( # This market has 2 dimensions. 
                       c("2024304e88665e58b3147b9bfd33fb1f"),  # k=1 x k=1 => (k+1) x (k+1) => 2 x 2 Market with 4 States
                       c("4bb76625de425c29ce52150cc5b3f160")
                       ),
             Description="Hillary and Congress",
             Tags=c("en", "UnitedStates", "Politics", "President", "Congress"),
             OwnerAd="1Loxo4RsiokFYXgpjc4CezGAmYnDwaydWh"
             )

names(Markets)

```

```{r Functions,echo=FALSE,message=FALSE}
#Tests
DisplayTest <- function() {
  print(Users$Alice)
  print(ShowPrices("Obama"))
  print(Markets$Obama$Shares)
}

Capture <- function(FUN="Buy",uID,ID,State,P) {
  #Captures the effect of trades on variables and captures this in a data frame.
  if(FUN=="Buy") Out <- Buy(uID,ID,State,P)
  if(FUN=="Sell") Out <- Sell(uID,ID,State,P)
  if(length(Out)==1) DOut <- data.frame("SharesTraded"=0,"TradeCost"=0,"MarketPrice"=ShowPrices(ID)[State],"Cash"=Users[[uID]]$Cash)
  if(length(Out)==2) DOut <- data.frame("SharesTraded"=Out[1],"TradeCost"=Out[2],"MarketPrice"=P,"Cash"=Users[[uID]]$Cash)
  return(DOut)
}

EmbellishRows <- function(DataIn) {
  DataIn$Time <- 1:nrow(DataIn)
  DataIn$SharesOwned <- cumsum(DataIn$SharesTraded)
  DataIn$TotalPaid <- cumsum(DataIn$TradeCost)
  DataIn$PriceChange <- c(diff(DataIn$MarketPrice),NA)
  return(DataIn)
}

ResetAlice <- function() if(ShowPrices("Obama")[1]!=.5) Sell("Alice","Obama",1,.5)

CaptureSequence <- function(Sequence) {
  ResetAlice()
  DataOut <- data.frame("SharesTraded"=0,"TradeCost"=0,"MarketPrice"=0,"Cash"=0)
  for(i in 1:(length(Sequence))) {
    if(Sequence[i]<ShowPrices("Obama")[1]) DataOut <- rbind(DataOut,Capture('Sell',"Alice","Obama",1,Sequence[i]))
    if(Sequence[i]>=ShowPrices("Obama")[1]) DataOut <- rbind(DataOut,Capture('Buy',"Alice","Obama",1,Sequence[i]))
    }
  return(DataOut[-1,])
}



MarketVisual <- function(Data) {
  library(ggplot2)
  library(reshape)
  
  mData <- melt(Data[,c(2,1,8,3,6,7,5)],id.vars="Time")
  
  P1 <- ggplot(mData,aes(x=Time,y=value)) +
    geom_point()+geom_line()+
    facet_grid(variable~.,scales="free_y")
  
  print(P1)
}


```

Basics
-----------------------
```{r Tests1}

ShowPrices("Obama")
#  d1.No d1.Yes 
#    0.5    0.5 
ShowPrices("Hillary")
#        d2.No d2.Yes
# d1.No   0.25   0.25
# d1.Yes  0.25   0.25

QueryMove("Obama",State=1,P=.6) #
# [1] 0.4054651 
QueryMove("Hillary",State=3,P=.30) #higher B increases liquidity
# [1] 0.6282861

QueryCost("Obama",State=2,S=1) #cost for 1 share
# [1] 0.6201145
QueryCost("Hillary",State=1,S=1)
# [1] 0.2899116

```

1 Trader, 1 Contract
------------------------
```{r Simple}

ResetAlice()

Simple <- CaptureSequence(
  c(.6,.7,.6,.8,.6,.5,.7,seq(.7,.99,length.out=15)))

MarketVisual(EmbellishRows(Simple))
# Produces a plot showing sample trades (0-10), and then a demo of linear incrase in Market Price corresponding to geometric growth in Trade Cost.
```

Trades Revealing Effect of LMSR
-----------------------------------
```{r LMRSEffect}

#Set 1
ResetAlice()
Users$Alice$Cash <- 1000 #lots of cash
Markets$Obama$Shares[1]  <- 10 #force possibility of lower price
Markets$Obama$Shares[2]  <- 10 #force possibility of lower price

MarketVisual(EmbellishRows(CaptureSequence(seq(.5,.95,length.out=30))))
# Graphic: linear incrase in Market Price (ie "Price Change") corresponds to geometric growth in Trade Cost.


#Self-Financing Effect
ResetAlice()
SFE <- EmbellishRows(CaptureSequence(c(seq(.5,.05,length.out=25),seq(.1,.5,length.out=4),seq(.5,.95,length.out=15))))
SFE$CostPerShare <- SFE$TradeCost/SFE$SharesTraded
plot(TradeCost~MarketPrice , data=SFE,main="The 'Self-Financing Effect'",sub="Rising cost to increase MarketPrice by exactly 0.01551724.",xlim=c(.55,1))
plot(CostPerShare~MarketPrice , data=SFE,main="The 'Self-Financing Effect II'",sub="Each share (eventually worth either $0 or $1) costs approximately its own price.")

#In fact, setting the probability to 1 is always impossible (very realistic).
QueryMoveCost("Obama",1,1)
# [1] Inf


#Set 2
ResetAlice()

dLMSR2 <- rbind(
            Capture('Buy', "Alice","Obama",1,0.8181818),
            Capture('Buy', "Alice","Obama",1,0.90000),
            Capture('Buy', "Alice","Obama",1,0.99000),
            Capture('Buy', "Alice","Obama",1,0.99900),
            Capture('Buy', "Alice","Obama",1,0.99990))
#Notice same cost to move for (1/10)th price change.
ResetAlice()

dLMSR3 <- rbind(
            Capture('Buy', "Alice","Obama",1,0.8181818),
            Capture('Buy', "Alice","Obama",1,0.900000),
            Capture('Buy', "Alice","Obama",1,0.940000),
            Capture('Buy', "Alice","Obama",1,0.970000),
            Capture('Buy', "Alice","Obama",1,0.990000),
            Capture('Buy', "Alice","Obama",1,0.991000),
            Capture('Buy', "Alice","Obama",1,0.992000),
            Capture('Buy', "Alice","Obama",1,0.993000),
            Capture('Buy', "Alice","Obama",1,0.994000),
            Capture('Buy', "Alice","Obama",1,0.995000),
            Capture('Buy', "Alice","Obama",1,0.996000),
            Capture('Buy', "Alice","Obama",1,0.997000),
            Capture('Buy', "Alice","Obama",1,0.998000),
            Capture('Buy', "Alice","Obama",1,0.999000),
            Capture('Buy', "Alice","Obama",1,0.999900),
            Capture('Buy', "Alice","Obama",1,0.999999),
            Capture('Buy', "Alice","Obama",1,0.99999999))


dLMSR2 <- dLMSR2[-1,] # .5 to .81818 is nonrepresentative of this effect
dLMSR3 <- dLMSR3[-1,] 


plot(MarketPrice~Cash,main="Price impact from spending 2.302",data=dLMSR2,xlim=c(999,988),axes=FALSE)
lines(dLMSR3$Cash,dLMSR3$MarketPrice)
axis(side = 2, at = c(.9,.99,.999,.9999),las=2)
axis(side = 1, at = seq(998,980,by=-2.302),las=2)
box()
# Graphic: Although we've spent the same amount (2.302), price increase is geometrically-decreasing (+0.0900, +0.0090, +0.0009, ...)

```

Redemptions
-------------------------------

```{r Redeptions}

Buy(uID="Alice",ID="Obama",State=2,P=.7,Verbose=TRUE)
# [1] "Calulating Required Shares... 0.847297860387203"
# [1] "Determining Cost of Trade... 0.510825623765991"
# [1] "Fee: 0.00510825623765991"
# [1] "Bought 0.847297860387203 for 0.51593388000365 ."
# [1] 0.8472979 0.5159339
ShowPrices("Obama")
#  d1.No d1.Yes 
#    0.3    0.7 

Redeem(uID="Alice",ID="Obama",State=2,S=.8,Verbose=TRUE)
# [1] "You cannot redeem (sell) using this function until there is a consensus about the outcome."
# [1] -1

Markets$Obama$State <- 2  # obviously, never would the user set or edit this.

Redeem(uID="Alice",ID="Obama",State=2,S=.8,Verbose=TRUE)
# [1] "This market contains Disputed Decisions. Funds are frozen during audit."
# [1] -2

Markets$Obama$State <- 3  # contract's Decisions are all finished  (would be set automatically)
GetFinalPrices(Markets$Obama) # Requres that all Decisions be resolved. (These results were assumed).
#  d1.No d1.Yes 
#      0      1 

Redeem(uID="Alice",ID="Obama",State=2,S=.84,Verbose=TRUE)
# [1] "FinalSold 0.84 for 0.84 ."
# [1] -0.84   -0.84 

Users$Alice
# $Cash
# [1] 10.32407
# 
# $Obama
#     State2 
# 0.00729786 

Markets$Obama$Balance
# [1] 0.3639728

Markets$Obama$Shares
#      d1.No     d1.Yes 
# 0.00000000 0.00729786 

```

